[project]
name = "target-salesforce"
version = "2.0.0"
description = "`target-salesforce` is a Singer target for Salesforce, built with the Meltano SDK for Singer Targets."
readme = "README.md"
authors = [{ name = "Dan Ladd" }]
requires-python = ">=3.10"
license = "Apache-2.0"
keywords = [
    "ELT",
    "Salesforce",
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "requests~=2.34.2",
    "simple-salesforce~=1.12.10",
    "singer-sdk~=0.54.5",
]

[project.scripts]
# CLI declaration
target-salesforce = 'target_salesforce.target:TargetSalesforce.cli'

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" },
    "mypy>=2.1.0",
    "types-requests>=2.33.0",
]
lint = [
    "ruff>=0.16.1",
]
test = [
    "pytest>=9.1.1",
    "singer-sdk[testing]",
]

[tool.uv]
default-groups = "all"

[tool.pytest.ini_options]
addopts = [
    "--durations=10",
]
testpaths = ["target_salesforce/tests"]

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
ignore = [
    "ANN001",  # missing-type-function-argument
    "ANN002",  # missing-type-args
    "ANN003",  # missing-type-kwargs
    "ANN201",  # missing-return-type-undocumented-public-function
    "ANN202",  # missing-return-type-private-function
    "COM812",  # missing-trailing-comma
]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.isort]
known-first-party = ["target_salesforce"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"target_salesforce/tests/*" = [
    "S101",  # assert
]

[build-system]
requires = [
    "hatchling>=1.31.0,<2",
]
build-backend = "hatchling.build"
